### PR TITLE
Use {idleTimeout:0} option

### PR DESCRIPTION
**Pull request by guest271314**
Use {idleTimeout:0} option https://deno.land/api@v1.37.2?s=Deno.UpgradeWebSocketOptions#prop_idleTimeout

### CODE REVIEW

**Comment by caramboleyo** [comment]
oh i did not see that, what was it?

**Comment by caramboleyo** [comment]
This does in fact help, the hanging socket still happens randomly but not so often

**Comment by guest271314** [comment]
The last time I checked the timeour for self-signed certificates was fixed.

**Comment by guest271314** [comment]
> well its not and with the update several other problems occurred.

It was fixed the last time I checked. Just checked again and there is no idle timeout, even without `{idleTimeout: 0}` set. 

> mostly performance issues under heavy load.

I have no idea what you are doing in your code. 

> i switched back to nodejs and rewrite my whole platform now.

Well, Node.js does not have a built-in WebSocket server, so you are going to be using third-party code.

> deno is not for web developers, its for precompilers and frontend SPA weirdos.

I am not tethered to Deno or Node.js. I use the appropriate tool for the given task. Could be txiki.js, could be QuickJS, could be Deno or Node.js, or could be `wasmtime` for WASM in WASI.

**Comment by guest271314** [comment]
Here is Deno's WebSocket server with a client remaining connected for 38 minutes until I closed the connection.


deno_ws_server.js
```
#!/usr/bin/env -S /home/user/bin/deno run -A --unsafely-ignore-certificate-errors=localhost --unstable --v8-flags="--expose-gc,--jitless"

(async () => {
  // https://medium.com/deno-the-complete-reference/http-2-in-deno-f825251a5ab2
  for await (
    const conn of Deno.listenTls({
      port: 8000,
      certFile: "./cert.pem",
      keyFile: "./cert.key",
      alpnProtocols: ["h2", "http/1.1"],
    })
  ) {
    for await (
      const {
        request,
        respondWith,
      } of Deno.serveHttp(conn)
    ) {
      const {
        socket,
        response,
      } = Deno.upgradeWebSocket(request);
      socket.addEventListener("open", (event) => {
        console.log(event.type);
      });
      socket.addEventListener("message", (event) => {
        socket.send(event.data);
      });
      socket.addEventListener("close", (event) => {
        console.log(event.type);
      });
      socket.addEventListener("error", (event) => {
        console.log(event.message);
      });
      respondWith(response);
    }
  }
})().catch(async (e) => {
  console.log(e);
});
```

browser client

```
var wss = new WebSocketStream("wss://localhost:8000");
console.log(wss);
wss.closed.catch((e) => {
  console.log(e);
});

wss.opened.catch((e) => {
  console.log(e);
});

var {
  readable,
  writable,
} = await wss.opened;
var now;
var writer = writable.getWriter();
var abortable = new AbortController();
var controller;
var {
  signal,
} = abortable;
writer.closed.then(() => console.log("writer closed")).catch(() =>
  console.log("writer closed error")
);
let minutes = 0;
readable.pipeThrough(new TextDecoderStream()).pipeTo(
  new WritableStream({
    async start(c) {
      console.log(c);
      (async () => {
        while (!c.signal.aborted) {
          try {
            await new Promise((resolve, reject) => {
              c.signal.onabort = reject;
              setTimeout(resolve, 60000);
            });
            minutes++;
          } catch {
          } finally {
            console.log(minutes);
          }
        }
        console.log(c.signal.aborted);
      })();
      return controller = c;
    },
    write(v) {
      console.log(v);
    },
    close() {
      console.log("Socket closed");
    },
    abort(reason) {
      console.log({
        reason,
      });
    },
  }),
  {
    signal,
  },
).then(() => console.log("pipeThrough, pipeTo Promise")).catch(() =>
  console.log("caught")
);
```

Screenshot_2024-01-02_18-52-19

**Comment by caramboleyo** [comment]
i have no idea what you do with that client, the default implementation looks like that:
```javascript
const socket = new WebSocket('<url>');
socket.onmessage = function(event) {
	const { data } = event;
}
```

and that one is supposed to work and my implementation of it is quite simple:
http://hybriqor.worldapi.org/code/0.8.0/client/web-socket-client.js

server nothing fancy too:
http://hybriqor.worldapi.org/code/0.8.0/server/web-socket-server.js

**Comment by caramboleyo** [comment]
but your code seems to send frequent pings

**Comment by guest271314** [comment]
Doesn't send any pings. The code logs every minute to test how long the WebSocket connection stays live without any data sent to or from the server.

**Comment by guest271314** [comment]
That's a WebSocket connection open and active 38 minutes without any data being sent to and from the server. Logged client side on Chromium 122.

**Comment by guest271314** [comment]
Deno is on version 1.39.1. Run `deno upgrade`.

**Comment by caramboleyo** [comment]
?

**Comment by guest271314** [comment]
> but why does it work properly until version 1.32.3

Sounds like you're running deno version 1.32.3?

**Comment by caramboleyo** [comment]
The WebSockets ran perfectly until version 1.32.3
so yes, i am always going back to that version because after that it no longer worked.
(When i test if it works now i upgrade to the current version)

**Comment by guest271314** [comment]
It works now as to not timing out when self-signed certificates are used with wss:. That's all I'm commenting about here.

**Pull request closed without merging**
